name: Dev Branch Test

on:
  push:
    branches: [dev]
    paths-ignore:
      - "**.md"
      - ".gitignore"
  # Allow manual trigger from the Actions tab
  workflow_dispatch:

# Add permissions for GitHub token
permissions:
  contents: read
  packages: read
  # This is used to upload artifacts
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Enable caching on subsequent runs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate test private key
        run: |
          mkdir -p keys
          openssl genrsa -out keys/private.pem 2048
          chmod 600 keys/private.pem

      - name: Install crx globally
        run: npm install -g crx

      - name: Package extension
        run: |
          mkdir -p dist
          VERSION=$(grep -o '"version": "[^"]*"' manifest.json | cut -d'"' -f4)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "Current directory contents:"
          ls -la
          echo "Packaging extension..."
          crx pack . --zip-output "dist/goodreads-where-to-buy-${VERSION}-dev-${TIMESTAMP}.zip" \
                    --private-key keys/private.pem \
                    --output "dist/goodreads-where-to-buy-${VERSION}-dev-${TIMESTAMP}.crx"
          echo "Dist directory contents:"
          ls -la dist/
          echo "Extension version: ${VERSION}-dev-${TIMESTAMP}"

      # Alternative packaging method if crx fails
      - name: Alternative packaging if crx fails
        if: ${{ failure() }}
        run: |
          echo "Using alternative packaging method..."
          mkdir -p dist
          VERSION=$(grep -o '"version": "[^"]*"' manifest.json | cut -d'"' -f4)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          zip -r "dist/goodreads-where-to-buy-${VERSION}-dev-${TIMESTAMP}.zip" . -x "node_modules/*" -x "dist/*" -x ".git/*" -x "keys/*"
          echo "Dist directory contents after alternative method:"
          ls -la dist/

      - name: Upload dev artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dev-build
          path: dist/*
          retention-days: 3
          if-no-files-found: warn
